namespace BinarySerializer.Ray1
{
    /// <summary>
    /// The object types for Rayman 2
    /// </summary>
    public enum R2_ObjType : ushort
    {
        TYPE_INVALID = 0, // Custom name (unallocated always object)
        TYPE_RAYMAN = 1,
        TYPE_POING = 2,
        TYPE_ONEUP = 3,
        TYPE_JAUGEUP = 4,
        TYPE_NOVA2 = 5,
        TYPE_GENERATING_DOOR = 6,
        TYPE_DESTROYING_DOOR = 7, // Unused
        TYPE_BOUM = 8,
        TYPE_MINE = 9, // Custom name
        TYPE_EXPLOSION = 10,
        TYPE_POING_REFLECT = 11, // Custom name
        TYPE_REDUCTEUR = 12, // Unused
        TYPE_HOOK = 13, // Custom name
        TYPE_0E = 14, // Unused - custom name (some moving lever/platform the fist can interact with and spawn TYPE_0F)
        TYPE_0F = 15, // Unused - custom name
        TYPE_10 = 16, // Unused - custom name
        TYPE_11 = 17, // Unused - custom name
        TYPE_PLATFORM = 18,
        TYPE_PT_GRAPPIN = 19,
        TYPE_14 = 20, // Unused - custom name (spawns TYPE_15)
        TYPE_15 = 21, // Unused - custom name
        TYPE_16 = 22, // Unused - custom name (enemy)
        TYPE_17 = 23, // Unused - custom name (platform which seems to also scroll the camera)
        TYPE_TELEPORTER = 24, // Custom name
        TYPE_19 = 25, // Unused - custom name (spawns more of itself)
        TYPE_1A = 26, // Unused - custom name (enemy)
        TYPE_SIGNPOST = 27,
        TYPE_MOVE_AUTOJUMP_PLAT = 28, // Unused
        TYPE_1D = 29, // Unused - custom name
        TYPE_1E = 30, // Unused - custom name (platform)
        TYPE_1F = 31, // Unused - custom name (platform)
        TYPE_20 = 32, // Unused - custom name
        TYPE_21 = 33, // Unused - custom name
        TYPE_SCARED_PLATFORM = 34, // Custom name
        TYPE_23 = 35, // Unused - custom name (platform)
        TYPE_TRAP_CUBE = 36, // Custom name
        TYPE_25 = 37, // Unused - custom name (platform)
        TYPE_TRAMPOLINE = 38, // Custom name
        TYPE_27 = 39, // Unused - custom name (seems to spawn and perhaps interact with hook)
        TYPE_28 = 40, // Unused - custom name (moves horizontally and rotates)
        TYPE_29 = 41, // Unused - custom name
        TYPE_2A = 42, // Unused - custom name (moves and eventually explodes)
        TYPE_2B = 43, // Unused - custom name (changes state if it detects Rayman or the fist)
        TYPE_2C = 44, // Unused - custom name (modifies tile graphics)
        TYPE_2D = 45, // Unused - custom name (enemy)
        TYPE_2E = 46, // Unused - custom name
        TYPE_2F = 47, // Unused - custom name (platform)
        TYPE_TRIGGER = 48, // Custom name
        TYPE_RAY_POS = 49,
        TYPE_32 = 50, // Unused - custom name (rotates)
        TYPE_BOLTS = 51, // Custom name
        TYPE_POTION = 52, // Custom name
        TYPE_35 = 53, // Unused - custom name
        TYPE_36 = 54, // Unused - custom name (enemy)
        TYPE_37 = 55, // Unused - custom name (platform)
        TYPE_ROTATING_CUBE = 56, // Custom name
        TYPE_39 = 57, // Unused - custom name (enemy which moves like a platform)
        TYPE_3A = 58, // Unused - custom name
        TYPE_3B = 59, // Unused - custom name (enabled place ray and checks block types)
        TYPE_3C = 60, // Unused - custom name (enemy)
        TYPE_3D = 61, // Unused - custom name (enemy which spawns TYPE_3E)
        TYPE_3E = 62, // Unused - custom name (something which explodes)
        TYPE_3F = 63, // Unused - custom name (platform)
        TYPE_40 = 64, // Unused - custom name (damages Rayman)
        TYPE_41 = 65, // Unused - custom name (moves based on fist charge)
        TYPE_42 = 66, // Unused - custom name (damages Rayman, same function as TYPE_43 and TYPE_44)
        TYPE_43 = 67, // Unused - custom name
        TYPE_44 = 68, // Unused - custom name
        TYPE_45 = 69, // Unused - custom name (spawns TYPE_46)
        TYPE_46 = 70, // Unused - custom name
        TYPE_47 = 71, // Unused - custom name (enemy)
        TYPE_48 = 72, // Unused - custom name (interacts with hook)
        TYPE_49 = 73, // Unused - custom name (enemy which blows Rayman with wind, like trumpets?)
        TYPE_4A = 74, // Unused - custom name (damages Rayman)
        TYPE_4B = 75, // Unused - custom name
        TYPE_SPLASH = 76,
        TYPE_4D = 77, // Unused - custom name
        TYPE_4E = 78, // Unused - custom name
        TYPE_4F = 79, // Unused - custom name
        TYPE_50 = 80, // Unused - custom name (damages Rayman, has a lot of code - maybe a boss?)
        TYPE_CANNON = 81, // Custom name
        TYPE_VIEW_FINDER = 82, // Custom name
        TYPE_CANNONBALL = 83, // Custom name
        TYPE_54 = 84, // Unused - custom name (rotates)
        TYPE_55 = 85, // Unused - custom name
        TYPE_56 = 86, // Unused - custom name (special object for ray mode 5)
        TYPE_57 = 87, // Unused - custom name
        TYPE_58 = 88, // Unused - custom name
        TYPE_59 = 89, // Unused - custom name (starts and ends ray mode 5)
        TYPE_5A = 90, // Unused - custom name (damages Rayman)
        TYPE_GUARD = 91, // Custom name
        TYPE_GUNSHOT = 92, // Custom name
        TYPE_5D = 93, // Unused - custom name (damages Rayman)
        TYPE_5E = 94, // Unused - custom name
        TYPE_DESTRUCTABLE_GROUND = 95, // Custom name
        TYPE_SMACKBX003 = 96, // Custom name
        TYPE_WIZ = 97,
        TYPE_DINO = 98, // Custom name
        TYPE_DINO_BREATH = 99, // Custom name
        TYPE_SMACKBX003_PART = 100, // Custom name
        TYPE_65 = 101, // Unused - custom name
        TYPE_SPARKLE = 102, // Custom name
        TYPE_GUNSHOT_EXPLOSION = 103, // Custom name
        TYPE_WATERFALL = 104 // Custom name
    }
}